### ISSUE TITLE
conference_layouts.conf  missing, conference mcu do not work

### ISSUE THREAD

**Issue by zlkk2013** [custompbx/custompbx#10]
conference_layouts.conf  setting can not found from custompbx,so freeswitch get info  like this:
<img width="977" alt="image" src="https://github.com/custompbx/custompbx/assets/9383384/1b7ec552-f893-4cc3-9b0c-64e91efef93d">
conference mcu can not find var video-layout-name value group:grid
fs log:
<img width="1331" alt="image" src="https://github.com/custompbx/custompbx/assets/9383384/489f72d0-ad5a-42e3-b592-a2b3dde3742a">

**Comment by zusrut** [comment]
Hello. Could you share more details - dialplan and configs for conference_layouts. It was not complete as I never used it an so tested. I'll fix this soon.

**Comment by zusrut** [comment]
fixed: cofig added.
@zlkk2013
