### ISSUE TITLE
Required install

### ISSUE THREAD

**Issue by enieber** [custompbx/custompbx#12]
Hi, this project is very nice, but  in documentation need add some things like:

Required:

- OS (debian based)
- dependencies:
  - make (apt install make)
  - curl (apt install curl)
  - wget (apt install wget)
  - nodejs 18 + npm (https://github.com/Schniz/fnm)
  - go lang (https://linuxcapable.com/how-to-install-golang-go-on-debian-linux/)

**Comment by zusrut** [comment]
Thanks for you feedback. I'll update documentation later.

**Comment by zusrut** [comment]
updated readme and makefile.
