### ISSUE TITLE
front end issue

### ISSUE THREAD

**Issue by Globalebill** [custompbx/custompbx#16]
file: runtime.fc1eeb77f673cd71.js

TypeError: v[e].call is not a function

angular v18.2.11

 return v[e].call(f.exports, f, f.exports, a),

**Comment by zusrut** [comment]
hi. it must be angular v17. i will update it up to 18 version later. @Globalebill

**Comment by Globalebill** [comment]
i have tried Angular CLI: 17.3.10 and Node: 18.20.5

same error and the login page wont load, the server is up and running

**Comment by Globalebill** [comment]
full error is

Uncaught TypeError: v[e].call is not a function
    at a (runtime.fc1eeb77f673cd71.js:1:143)
    at main.0886a8157c2b0672.js:1:1222859
    at r (runtime.fc1eeb77f673cd71.js:1:4470)
    at main.0886a8157c2b0672.js:1:59

**Comment by zusrut** [comment]
Well I just built it with command:
```
sudo make install
``` 
and everything works with no error.
my setup by command:
```
sudo make show
``` 
```
sudo make show
Timestamp: Fri Nov 15 01:24:02 CET 2024
Node Version: v23.2.0
Npm Version: 10.9.0
os: Linux
user: root
go_bindata: go-bindata: /usr/bin/go-bindata /usr/share/man/man8/go-bindata.8.gz
```

@Globalebill check if path correct for your setup and all js files were downloaded without any errors. If in your setup custompbx  is behind proxy under specific location in path - you probably need to change base-href(baseHref/APP_BASE_HREF) or deploy-url in angular(angular.json and app.module.ts) to have correct path to static files.

**Comment by Globalebill** [comment]
used v0.0.106a and error no longer showing
