### ISSUE TITLE
ACL lists

### ISSUE THREAD

**Issue by Globalebill** [custompbx/custompbx#18]
the ACL list in not allowing a Cidr added, disabling mod_xml_curl and running freeswitch the ACL list works as normal.

when using the ACL list in custompbx admin the same acl list is not allowing the incoming ip, debug info:
[DEBUG] sofia.c:10554 verifying acl "domains" for ip/port xxx.xxx.xxx.xxx
correct ip is in the "domains" acl in custompbx admin

**Comment by zusrut** [comment]
🤔 seems its because of empty domain attribute i just pushed a commit to fix this. @Globalebill could you rebuild and test?

**Comment by Globalebill** [comment]
hi, could you push a pre compiled release with the fix ? as we had issues with building from source and getting the right npm versions etc.. but the pre compiled works fine

**Comment by zusrut** [comment]
@Globalebill try [v0.0.106b](https://github.com/custompbx/custompbx/releases/tag/v0.0.106b)
