### ISSUE TITLE
The ws IP in config.json has been changed, but the web side wss is still 127.0.0.1:8080/ws

### ISSUE THREAD

**Issue by mrtian** [custompbx/custompbx#8]
The ws IP in config.json has been changed, but the web side wss is still 127.0.0.1:8080/ws

**Comment by zusrut** [comment]
Hello. 
If you build it manual or with makefile.
Create `src/cweb-app/env.js` file  with content `export function getWs() { return 'wss://127.0.0.1:8080/ws'; }` replace ip and port to yours.
I will redo ws addressing soon.
Thanks.

**Comment by zusrut** [comment]
@mrtian pushed new release
